# Generated by Django 4.2.30 on 2026-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_milkcollection_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=20),
        ),
    ]
