# Generated by Django 4.2.30 on 2026-07-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_milkcollection_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='price_per_litre',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
