# Generated by Django 4.2 on 2026-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_milkcollection_price_per_litre'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
